[2024-09-04T03:29:41.915+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-09-04T03:29:41.941+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: query_statement.mysql_to_hook scheduled__2024-09-03T00:00:00+00:00 [queued]>
[2024-09-04T03:29:41.948+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: query_statement.mysql_to_hook scheduled__2024-09-03T00:00:00+00:00 [queued]>
[2024-09-04T03:29:41.949+0000] {taskinstance.py:2306} INFO - Starting attempt 3 of 6
[2024-09-04T03:29:41.962+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): mysql_to_hook> on 2024-09-03 00:00:00+00:00
[2024-09-04T03:29:41.970+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=527) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-09-04T03:29:41.971+0000] {standard_task_runner.py:64} INFO - Started process 531 to run task
[2024-09-04T03:29:41.970+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'query_statement', 'mysql_to_hook', 'scheduled__2024-09-03T00:00:00+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/first_task.py', '--cfg-path', '/tmp/tmp116k2h8b']
[2024-09-04T03:29:41.972+0000] {standard_task_runner.py:91} INFO - Job 8: Subtask mysql_to_hook
[2024-09-04T03:29:41.984+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-09-04T03:29:42.010+0000] {task_command.py:426} INFO - Running <TaskInstance: query_statement.mysql_to_hook scheduled__2024-09-03T00:00:00+00:00 [running]> on host 9927162d0e47
[2024-09-04T03:29:42.071+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='congdat' AIRFLOW_CTX_DAG_ID='query_statement' AIRFLOW_CTX_TASK_ID='mysql_to_hook' AIRFLOW_CTX_EXECUTION_DATE='2024-09-03T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-03T00:00:00+00:00'
[2024-09-04T03:29:42.255+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-09-04T03:29:42.269+0000] {base.py:84} INFO - Using connection ID 'mysql_default' for task execution.
[2024-09-04T03:29:42.272+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-09-04T03:29:42.273+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/first_task.py", line 30, in mysql_to_hook
    cursor.execute("select * from bai_test.hpg")
  File "/home/airflow/.local/lib/python3.12/site-packages/MySQLdb/cursors.py", line 179, in execute
    res = self._query(mogrified_query)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/MySQLdb/cursors.py", line 330, in _query
    db.query(q)
  File "/home/airflow/.local/lib/python3.12/site-packages/MySQLdb/connections.py", line 261, in query
    _mysql.connection.query(self, query)
MySQLdb.ProgrammingError: (1146, "Table 'bai_test.hpg' doesn't exist")
[2024-09-04T03:29:42.281+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=query_statement, task_id=mysql_to_hook, run_id=scheduled__2024-09-03T00:00:00+00:00, execution_date=20240903T000000, start_date=20240904T032941, end_date=20240904T032942
[2024-09-04T03:29:42.294+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 8 for task mysql_to_hook ((1146, "Table 'bai_test.hpg' doesn't exist"); 531)
[2024-09-04T03:29:42.345+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-09-04T03:29:42.355+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-04T03:29:42.356+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-09-04T09:19:46.651+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-09-04T09:19:46.682+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: query_statement.mysql_to_hook scheduled__2024-09-03T00:00:00+00:00 [queued]>
[2024-09-04T09:19:46.691+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: query_statement.mysql_to_hook scheduled__2024-09-03T00:00:00+00:00 [queued]>
[2024-09-04T09:19:46.692+0000] {taskinstance.py:2306} INFO - Starting attempt 3 of 6
[2024-09-04T09:19:46.705+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): mysql_to_hook> on 2024-09-03 00:00:00+00:00
[2024-09-04T09:19:46.713+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=931) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-09-04T09:19:46.712+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'query_statement', 'mysql_to_hook', 'scheduled__2024-09-03T00:00:00+00:00', '--job-id', '91', '--raw', '--subdir', 'DAGS_FOLDER/first_task.py', '--cfg-path', '/tmp/tmp776aaea9']
[2024-09-04T09:19:46.714+0000] {standard_task_runner.py:64} INFO - Started process 933 to run task
[2024-09-04T09:19:46.714+0000] {standard_task_runner.py:91} INFO - Job 91: Subtask mysql_to_hook
[2024-09-04T09:19:46.729+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-09-04T09:19:46.763+0000] {task_command.py:426} INFO - Running <TaskInstance: query_statement.mysql_to_hook scheduled__2024-09-03T00:00:00+00:00 [running]> on host 82f647023843
[2024-09-04T09:19:46.842+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='congdat' AIRFLOW_CTX_DAG_ID='query_statement' AIRFLOW_CTX_TASK_ID='mysql_to_hook' AIRFLOW_CTX_EXECUTION_DATE='2024-09-03T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-03T00:00:00+00:00'
[2024-09-04T09:19:46.985+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-09-04T09:19:47.005+0000] {base.py:84} INFO - Using connection ID 'mysql_default' for task execution.
[2024-09-04T09:19:47.041+0000] {first_task.py:37} INFO - Saved hpg data in text file get_orders.txt
[2024-09-04T09:19:47.042+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-09-04T09:19:47.042+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-09-04T09:19:47.055+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=query_statement, task_id=mysql_to_hook, run_id=scheduled__2024-09-03T00:00:00+00:00, execution_date=20240903T000000, start_date=20240904T091946, end_date=20240904T091947
[2024-09-04T09:19:47.128+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-09-04T09:19:47.151+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-04T09:19:47.154+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
