[2024-09-04T09:17:46.418+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-09-04T09:17:46.453+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: query_statement.mysql_to_hook manual__2024-09-04T09:15:43.220572+00:00 [queued]>
[2024-09-04T09:17:46.464+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: query_statement.mysql_to_hook manual__2024-09-04T09:15:43.220572+00:00 [queued]>
[2024-09-04T09:17:46.464+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 6
[2024-09-04T09:17:46.477+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): mysql_to_hook> on 2024-09-04 09:15:43.220572+00:00
[2024-09-04T09:17:46.484+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=796) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-09-04T09:17:46.485+0000] {standard_task_runner.py:64} INFO - Started process 798 to run task
[2024-09-04T09:17:46.484+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'query_statement', 'mysql_to_hook', 'manual__2024-09-04T09:15:43.220572+00:00', '--job-id', '90', '--raw', '--subdir', 'DAGS_FOLDER/first_task.py', '--cfg-path', '/tmp/tmpacg42iyl']
[2024-09-04T09:17:46.486+0000] {standard_task_runner.py:91} INFO - Job 90: Subtask mysql_to_hook
[2024-09-04T09:17:46.500+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-09-04T09:17:46.532+0000] {task_command.py:426} INFO - Running <TaskInstance: query_statement.mysql_to_hook manual__2024-09-04T09:15:43.220572+00:00 [running]> on host 82f647023843
[2024-09-04T09:17:46.738+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='congdat' AIRFLOW_CTX_DAG_ID='query_statement' AIRFLOW_CTX_TASK_ID='mysql_to_hook' AIRFLOW_CTX_EXECUTION_DATE='2024-09-04T09:15:43.220572+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-04T09:15:43.220572+00:00'
[2024-09-04T09:17:46.739+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-09-04T09:17:46.756+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-09-04T09:17:46.765+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/first_task.py", line 28, in mysql_to_hook
    conn = hook.get_conn()
           ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/mysql/hooks/mysql.py", line 188, in get_conn
    conn = self.connection or self.get_connection(getattr(self, self.conn_name_attr))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 519, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `mysql_default` isn't defined
[2024-09-04T09:17:46.771+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=query_statement, task_id=mysql_to_hook, run_id=manual__2024-09-04T09:15:43.220572+00:00, execution_date=20240904T091543, start_date=20240904T091746, end_date=20240904T091746
[2024-09-04T09:17:46.782+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 90 for task mysql_to_hook (The conn_id `mysql_default` isn't defined; 798)
[2024-09-04T09:17:46.819+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-09-04T09:17:46.835+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-04T09:17:46.836+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
