[2024-09-03T09:38:44.304+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-09-03T09:38:44.332+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: import_csv_to_mysql.import_Nhan_vien manual__2024-09-03T09:37:38.383526+00:00 [queued]>
[2024-09-03T09:38:44.341+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: import_csv_to_mysql.import_Nhan_vien manual__2024-09-03T09:37:38.383526+00:00 [queued]>
[2024-09-03T09:38:44.341+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 6
[2024-09-03T09:38:44.359+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): import_Nhan_vien> on 2024-09-03 09:37:38.383526+00:00
[2024-09-03T09:38:44.368+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=2842) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-09-03T09:38:44.368+0000] {standard_task_runner.py:64} INFO - Started process 2849 to run task
[2024-09-03T09:38:44.368+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'import_csv_to_mysql', 'import_Nhan_vien', 'manual__2024-09-03T09:37:38.383526+00:00', '--job-id', '32', '--raw', '--subdir', 'DAGS_FOLDER/first_task.py', '--cfg-path', '/tmp/tmpfx1uys2n']
[2024-09-03T09:38:44.369+0000] {standard_task_runner.py:91} INFO - Job 32: Subtask import_Nhan_vien
[2024-09-03T09:38:44.383+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-09-03T09:38:44.413+0000] {task_command.py:426} INFO - Running <TaskInstance: import_csv_to_mysql.import_Nhan_vien manual__2024-09-03T09:37:38.383526+00:00 [running]> on host 6f6575553fe4
[2024-09-03T09:38:44.692+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='congdat' AIRFLOW_CTX_DAG_ID='import_csv_to_mysql' AIRFLOW_CTX_TASK_ID='import_Nhan_vien' AIRFLOW_CTX_EXECUTION_DATE='2024-09-03T09:37:38.383526+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-03T09:37:38.383526+00:00'
[2024-09-03T09:38:44.693+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-09-03T09:38:44.703+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-09-03T09:38:44.704+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/import_csv.py", line 13, in import_csv_to_mysql
    data = pd.read_csv(file_path)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 948, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 611, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1448, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1705, in _make_engine
    self.handles = get_handle(
                   ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 863, in get_handle
    handle = open(
             ^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\Intern\\Yeucau3\\Scheduler\\dags/Nhan_vien.csv'
[2024-09-03T09:38:44.713+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=import_csv_to_mysql, task_id=import_Nhan_vien, run_id=manual__2024-09-03T09:37:38.383526+00:00, execution_date=20240903T093738, start_date=20240903T093844, end_date=20240903T093844
[2024-09-03T09:38:44.729+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 32 for task import_Nhan_vien ([Errno 2] No such file or directory: 'D:\\Intern\\Yeucau3\\Scheduler\\dags/Nhan_vien.csv'; 2849)
[2024-09-03T09:38:44.783+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-09-03T09:38:44.790+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
