[2024-09-03T14:50:25.393+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-09-03T14:50:25.427+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: import_csv_to_mysql.import_csv_San_pham manual__2024-09-03T09:49:20.042457+00:00 [queued]>
[2024-09-03T14:50:25.438+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: import_csv_to_mysql.import_csv_San_pham manual__2024-09-03T09:49:20.042457+00:00 [queued]>
[2024-09-03T14:50:25.438+0000] {taskinstance.py:2306} INFO - Starting attempt 3 of 4
[2024-09-03T14:50:25.456+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): import_csv_San_pham> on 2024-09-03 09:49:20.042457+00:00
[2024-09-03T14:50:25.471+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=19190) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-09-03T14:50:25.474+0000] {standard_task_runner.py:64} INFO - Started process 19204 to run task
[2024-09-03T14:50:25.471+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'import_csv_to_mysql', 'import_csv_San_pham', 'manual__2024-09-03T09:49:20.042457+00:00', '--job-id', '100', '--raw', '--subdir', 'DAGS_FOLDER/import_csv_to_mysql_dag.py', '--cfg-path', '/tmp/tmp9g34shs3']
[2024-09-03T14:50:25.476+0000] {standard_task_runner.py:91} INFO - Job 100: Subtask import_csv_San_pham
[2024-09-03T14:50:25.497+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-09-03T14:50:25.530+0000] {task_command.py:426} INFO - Running <TaskInstance: import_csv_to_mysql.import_csv_San_pham manual__2024-09-03T09:49:20.042457+00:00 [running]> on host 7932644bd5dc
[2024-09-03T14:50:25.958+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='congdat' AIRFLOW_CTX_DAG_ID='import_csv_to_mysql' AIRFLOW_CTX_TASK_ID='import_csv_San_pham' AIRFLOW_CTX_EXECUTION_DATE='2024-09-03T09:49:20.042457+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-03T09:49:20.042457+00:00'
[2024-09-03T14:50:25.960+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-09-03T14:50:25.979+0000] {logging_mixin.py:188} INFO - Error inserting data into table San_pham: (pymysql.err.OperationalError) (2003, "Can't connect to MySQL server on 'localhost' ([Errno 111] Connection refused)")
(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2024-09-03T14:50:25.980+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-09-03T14:50:25.981+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-09-03T14:50:25.990+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=import_csv_to_mysql, task_id=import_csv_San_pham, run_id=manual__2024-09-03T09:49:20.042457+00:00, execution_date=20240903T094920, start_date=20240903T145025, end_date=20240903T145025
[2024-09-03T14:50:26.050+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-09-03T14:50:26.059+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
